# Домашнє завдання 5: CTE та Materialized View

Тут я збираю набір ознак на рівні клієнта для ML на даних Olist. Спершу завантажую CSV і створюю typed-схему, потім рахую ознаки ланцюжком CTE, обходжу синтетичний referral-граф рекурсивним CTE, зберігаю результат у Materialized View і порівнюю плани `EXPLAIN (ANALYZE, BUFFERS)`. Дані взято з [Olist Brazilian E-Commerce Public Dataset](https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce) на Kaggle.

In [1]:
%pip install -q pgserver psycopg2-binary sqlalchemy pandas kagglehub sqlparse

import os
import pandas as pd
import pgserver
from sqlalchemy import create_engine, text

pg = pgserver.get_server('/tmp/hw5_pg', cleanup_mode='stop')
engine = create_engine(pg.get_uri(), future=True)

with engine.connect() as conn:
    print(conn.execute(text('SELECT version()')).scalar_one())

Note: you may need to restart the kernel to use updated packages.

PostgreSQL 16.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11), 64-bit

In [2]:
# Варіант A: якщо Kaggle credentials налаштовані
import kagglehub

dataset_dir = kagglehub.dataset_download('olistbr/brazilian-ecommerce')
print(dataset_dir)

# Варіант B: якщо CSV вже лежать у репозиторії або course archive
# dataset_dir = '/content/goit-rdb-hw-05/data/olist'

/home/dan/hw5-verify-venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to /home/dan/.cache/kagglehub/datasets/olistbr/brazilian-ecommerce/2.archive...

  0%|          | 0.00/42.6M [00:00<?, ?B/s]

  2%|▏         | 1.00M/42.6M [00:00<00:30, 1.41MB/s]

  5%|▍         | 2.00M/42.6M [00:01<00:24, 1.77MB/s]

  7%|▋         | 3.00M/42.6M [00:01<00:21, 1.93MB/s]

  9%|▉         | 4.00M/42.6M [00:02<00:20, 1.94MB/s]

 12%|█▏        | 5.00M/42.6M [00:02<00:19, 2.00MB/s]

 14%|█▍        | 6.00M/42.6M [00:03<00:18, 2.04MB/s]

 16%|█▋        | 7.00M/42.6M [00:03<00:17, 2.08MB/s]

 19%|█▉        | 8.00M/42.6M [00:04<00:17, 2.12MB/s]

 21%|██        | 9.00M/42.6M [00:04<00:16, 2.14MB/s]

 23%|██▎       | 10.0M/42.6M [00:05<00:16, 2.12MB/s]

 26%|██▌       | 11.0M/42.6M [00:05<00:16, 1.96MB/s]

 28%|██▊       | 12.0M/42.6M [00:06<00:15, 2.01MB/s]

 30%|███       | 13.0M/42.6M [00:06<00:15, 2.07MB/s]

 33%|███▎      | 14.0M/42.6M [00:07<00:14, 2.08MB/s]

 35%|███▌      | 15.0M/42.6M [00:07<00:13, 2.10MB/s]

 38%|███▊      | 16.0M/42.6M [00:08<00:13, 2.11MB/s]

 40%|███▉      | 17.0M/42.6M [00:08<00:12, 2.13MB/s]

 42%|████▏     | 18.0M/42.6M [00:09<00:11, 2.18MB/s]

 45%|████▍     | 19.0M/42.6M [00:09<00:11, 2.16MB/s]

 47%|████▋     | 20.0M/42.6M [00:10<00:11, 2.10MB/s]

 49%|████▉     | 21.0M/42.6M [00:10<00:10, 2.10MB/s]

 52%|█████▏    | 22.0M/42.6M [00:11<00:10, 2.02MB/s]

 54%|█████▍    | 23.0M/42.6M [00:11<00:09, 2.06MB/s]

 56%|█████▋    | 24.0M/42.6M [00:12<00:09, 2.10MB/s]

 59%|█████▊    | 25.0M/42.6M [00:12<00:08, 2.13MB/s]

 61%|██████    | 26.0M/42.6M [00:13<00:08, 2.14MB/s]

 63%|██████▎   | 27.0M/42.6M [00:13<00:07, 2.14MB/s]

 66%|██████▌   | 28.0M/42.6M [00:14<00:07, 2.07MB/s]

 68%|██████▊   | 29.0M/42.6M [00:14<00:07, 1.99MB/s]

 70%|███████   | 30.0M/42.6M [00:15<00:08, 1.61MB/s]

 73%|███████▎  | 31.0M/42.6M [00:16<00:09, 1.33MB/s]

 75%|███████▌  | 32.0M/42.6M [00:17<00:08, 1.30MB/s]

 77%|███████▋  | 33.0M/42.6M [00:18<00:07, 1.43MB/s]

 80%|███████▉  | 34.0M/42.6M [00:18<00:05, 1.61MB/s]

 82%|████████▏ | 35.0M/42.6M [00:19<00:04, 1.77MB/s]

 84%|████████▍ | 36.0M/42.6M [00:19<00:03, 1.87MB/s]

 87%|████████▋ | 37.0M/42.6M [00:20<00:03, 1.97MB/s]

 89%|████████▉ | 38.0M/42.6M [00:20<00:02, 2.06MB/s]

 91%|█████████▏| 39.0M/42.6M [00:21<00:01, 2.11MB/s]

 94%|█████████▍| 40.0M/42.6M [00:21<00:01, 2.18MB/s]

 96%|█████████▌| 41.0M/42.6M [00:21<00:00, 2.22MB/s]

 98%|█████████▊| 42.0M/42.6M [00:22<00:00, 2.27MB/s]

100%|██████████| 42.6M/42.6M [00:22<00:00, 2.31MB/s]

100%|██████████| 42.6M/42.6M [00:22<00:00, 1.97MB/s]

Extracting files...

/home/dan/.cache/kagglehub/datasets/olistbr/brazilian-ecommerce/versions/2

## 1. Отримання даних і raw-шар

П'ять CSV завантажуються через KaggleHub і без змін записуються в таблиці з суфіксом `_raw`. Це лише проміжний шар: з нього дані далі переносяться в typed-таблиці PostgreSQL. Для повторного запуску потрібен або доступ до датасету через KaggleHub (варіант A), або локальна копія CSV — тоді в комірці вище треба розкоментувати шлях із варіанта B.

In [3]:
files = {
    'olist_customers_raw': 'olist_customers_dataset.csv',
    'olist_orders_raw': 'olist_orders_dataset.csv',
    'olist_order_items_raw': 'olist_order_items_dataset.csv',
    'olist_products_raw': 'olist_products_dataset.csv',
    'olist_sellers_raw': 'olist_sellers_dataset.csv',
}

for table_name, file_name in files.items():
    path = os.path.join(dataset_dir, file_name)
    df = pd.read_csv(path)
    df.to_sql(table_name, engine, if_exists='replace', index=False, chunksize=10_000)
    print(table_name, df.shape)

olist_customers_raw (99441, 5)

olist_orders_raw (99441, 8)

olist_order_items_raw (112650, 7)

olist_products_raw (32951, 9)
olist_sellers_raw (3095, 4)

In [4]:
from sqlalchemy.exc import SQLAlchemyError
from IPython.display import display
import sqlparse

def execute_sql(
    sql,
    params=None,
    return_result=False,
    output_commands=True,
):
    """
    Execute a SQL script containing one or many SQL statements.

    Every statement is executed in order using the SAME database connection.

    Output:
    - SELECT / ... RETURNING -> displays a pandas DataFrame
    - INSERT / UPDATE / DELETE -> prints affected row count
    - CREATE / DROP / ALTER, etc. -> prints success
    - If output_commands=True, prints each SQL statement before execution
    - All statements are committed together if the whole script succeeds
    - On error, the transaction is rolled back

    Parameters
    ----------
    sql : str
        One SQL statement or a script containing multiple statements.

    params : dict, optional
        Named SQLAlchemy parameters, e.g. {"id": 1} for ":id".

    return_result : bool, default=False
        If True, returns a list with execution results.

    output_commands : bool, default=True
        If True, prints each SQL statement before executing it.

    Returns
    -------
    list[dict] | None
        One result dictionary per executed SQL statement if
        return_result=True, otherwise None.
    """

    statements = [
        statement.strip()
        for statement in sqlparse.split(sql)
        if statement.strip()
    ]

    outputs = []

    try:
        with engine.begin() as conn:
            for i, statement in enumerate(statements, start=1):
                print(f"\n{'=' * 70}")
                print(f"Statement {i}/{len(statements)}")
                print(f"{'=' * 70}")

                if output_commands:
                    print(statement)
                    print("-" * 70)

                result = conn.execute(
                    text(statement),
                    params or {}
                )

                if result.returns_rows:
                    rows = result.fetchall()

                    df = pd.DataFrame(
                        rows,
                        columns=result.keys()
                    )

                    display(df)

                    outputs.append({
                        "statement_number": i,
                        "statement": statement,
                        "type": "result_set",
                        "data": df,
                    })

                else:
                    rowcount = result.rowcount

                    if rowcount is not None and rowcount >= 0:
                        print(
                            "Command executed successfully. "
                            f"Rows affected: {rowcount}"
                        )
                    else:
                        print("Command executed successfully.")

                    outputs.append({
                        "statement_number": i,
                        "statement": statement,
                        "type": "command",
                        "rowcount": rowcount,
                    })

        print(
            f"\nFinished successfully: "
            f"{len(statements)} statement(s) executed."
        )

        if return_result:
            return outputs

        return None

    except SQLAlchemyError as e:
        print(f"\nSQL error while executing statement {i}:")
        print(statement)
        print(f"\n{e}")
        raise

## 2. Typed-схема й перевірка завантаження

У typed-таблицях задано типи колонок, первинні й зовнішні ключі, а також обмеження `NOT NULL` і `CHECK`. Дані з raw-шару переносяться через `INSERT ... SELECT`. Є одна дрібниця: у CSV колонки називаються `product_name_lenght` і `product_description_lenght` (з помилкою в самому датасеті), тому в `SELECT` використано саме ці назви, а в typed-схемі колонки названо правильно — `..._length`. Наприкінці рахую рядки в кожній таблиці.

In [5]:
execute_sql("""
DROP TABLE IF EXISTS olist_order_items CASCADE;
DROP TABLE IF EXISTS olist_orders      CASCADE;
DROP TABLE IF EXISTS olist_customers   CASCADE;
DROP TABLE IF EXISTS olist_products    CASCADE;
DROP TABLE IF EXISTS olist_sellers     CASCADE;

CREATE TABLE olist_customers (
    customer_id              TEXT PRIMARY KEY,
    customer_unique_id       TEXT NOT NULL,
    customer_zip_code_prefix INTEGER,
    customer_city            TEXT,
    customer_state           CHAR(2) NOT NULL
);

CREATE TABLE olist_orders (
    order_id                      TEXT PRIMARY KEY,
    customer_id                   TEXT NOT NULL REFERENCES olist_customers(customer_id),
    order_status                  TEXT NOT NULL,
    order_purchase_timestamp      TIMESTAMP NOT NULL,
    order_approved_at             TIMESTAMP,
    order_delivered_carrier_date  TIMESTAMP,
    order_delivered_customer_date TIMESTAMP,
    order_estimated_delivery_date TIMESTAMP,
    CHECK (order_status IN (
        'created', 'approved', 'invoiced', 'processing',
        'shipped', 'delivered', 'unavailable', 'canceled'
    ))
);

CREATE TABLE olist_products (
    product_id                 TEXT PRIMARY KEY,
    product_category_name      TEXT,
    product_name_length        INTEGER CHECK (product_name_length IS NULL OR product_name_length >= 0),
    product_description_length INTEGER CHECK (product_description_length IS NULL OR product_description_length >= 0),
    product_photos_qty         INTEGER CHECK (product_photos_qty IS NULL OR product_photos_qty >= 0),
    product_weight_g           INTEGER CHECK (product_weight_g IS NULL OR product_weight_g >= 0),
    product_length_cm          INTEGER CHECK (product_length_cm IS NULL OR product_length_cm >= 0),
    product_height_cm          INTEGER CHECK (product_height_cm IS NULL OR product_height_cm >= 0),
    product_width_cm           INTEGER CHECK (product_width_cm IS NULL OR product_width_cm >= 0)
);

CREATE TABLE olist_sellers (
    seller_id              TEXT PRIMARY KEY,
    seller_zip_code_prefix INTEGER,
    seller_city            TEXT,
    seller_state           CHAR(2) NOT NULL
);

CREATE TABLE olist_order_items (
    order_id            TEXT NOT NULL REFERENCES olist_orders(order_id),
    order_item_id       INTEGER NOT NULL,
    product_id          TEXT REFERENCES olist_products(product_id),
    seller_id           TEXT REFERENCES olist_sellers(seller_id),
    shipping_limit_date TIMESTAMP,
    price               NUMERIC(12, 2) CHECK (price IS NULL OR price >= 0),
    freight_value       NUMERIC(12, 2) CHECK (freight_value IS NULL OR freight_value >= 0),
    PRIMARY KEY (order_id, order_item_id)
);
""")

======================================================================
Statement 1/10
======================================================================
DROP TABLE IF EXISTS olist_order_items CASCADE;
----------------------------------------------------------------------
Command executed successfully.

======================================================================
Statement 2/10
======================================================================
DROP TABLE IF EXISTS olist_orders      CASCADE;
----------------------------------------------------------------------
Command executed successfully.

======================================================================
Statement 3/10
======================================================================
DROP TABLE IF EXISTS olist_customers   CASCADE;
----------------------------------------------------------------------
Command executed successfully.

======================================================================
Statement 4/10
======================================================================
DROP TABLE IF EXISTS olist_products    CASCADE;
----------------------------------------------------------------------
Command executed successfully.

======================================================================
Statement 5/10
======================================================================
DROP TABLE IF EXISTS olist_sellers     CASCADE;
----------------------------------------------------------------------
Command executed successfully.

======================================================================
Statement 6/10
======================================================================
CREATE TABLE olist_customers (
    customer_id              TEXT PRIMARY KEY,
    customer_unique_id       TEXT NOT NULL,
    customer_zip_code_prefix INTEGER,
    customer_city            TEXT,
    customer_state           CHAR(2) NOT NULL
);
----------------------------------------------------------------------
Command executed successfully.

======================================================================
Statement 7/10
======================================================================
CREATE TABLE olist_orders (
    order_id                      TEXT PRIMARY KEY,
    customer_id                   TEXT NOT NULL REFERENCES olist_customers(customer_id),
    order_status                  TEXT NOT NULL,
    order_purchase_timestamp      TIMESTAMP NOT NULL,
    order_approved_at             TIMESTAMP,
    order_delivered_carrier_date  TIMESTAMP,
    order_delivered_customer_date TIMESTAMP,
    order_estimated_delivery_date TIMESTAMP,
    CHECK (order_status IN (
        'created', 'approved', 'invoiced', 'processing',
        'shipped', 'delivered', 'unavailable', 'canceled'
    ))
);
----------------------------------------------------------------------
Command executed successfully.

======================================================================
Statement 8/10
======================================================================
CREATE TABLE olist_products (
    product_id                 TEXT PRIMARY KEY,
    product_category_name      TEXT,
    product_name_length        INTEGER CHECK (product_name_length IS NULL OR product_name_length >= 0),
    product_description_length INTEGER CHECK (product_description_length IS NULL OR product_description_length >= 0),
    product_photos_qty         INTEGER CHECK (product_photos_qty IS NULL OR product_photos_qty >= 0),
    product_weight_g           INTEGER CHECK (product_weight_g IS NULL OR product_weight_g >= 0),
    product_length_cm          INTEGER CHECK (product_length_cm IS NULL OR product_length_cm >= 0),
    product_height_cm          INTEGER CHECK (product_height_cm IS NULL OR product_height_cm >= 0),
    product_width_cm           INTEGER CHECK (product_width_cm IS NULL OR product_width_cm >= 0)
);
----------------------------------------------------------------------
Command executed successfully.

======================================================================
Statement 9/10
======================================================================
CREATE TABLE olist_sellers (
    seller_id              TEXT PRIMARY KEY,
    seller_zip_code_prefix INTEGER,
    seller_city            TEXT,
    seller_state           CHAR(2) NOT NULL
);
----------------------------------------------------------------------
Command executed successfully.

======================================================================
Statement 10/10
======================================================================
CREATE TABLE olist_order_items (
    order_id            TEXT NOT NULL REFERENCES olist_orders(order_id),
    order_item_id       INTEGER NOT NULL,
    product_id          TEXT REFERENCES olist_products(product_id),
    seller_id           TEXT REFERENCES olist_sellers(seller_id),
    shipping_limit_date TIMESTAMP,
    price               NUMERIC(12, 2) CHECK (price IS NULL OR price >= 0),
    freight_value       NUMERIC(12, 2) CHECK (freight_value IS NULL OR freight_value >= 0),
    PRIMARY KEY (order_id, order_item_id)
);
----------------------------------------------------------------------
Command executed successfully.

Finished successfully: 10 statement(s) executed.

In [6]:
execute_sql("""
INSERT INTO olist_customers
SELECT
    customer_id,
    customer_unique_id,
    customer_zip_code_prefix::INTEGER,
    customer_city,
    customer_state::CHAR(2)
FROM olist_customers_raw;

INSERT INTO olist_orders
SELECT
    order_id,
    customer_id,
    order_status,
    order_purchase_timestamp::TIMESTAMP,
    order_approved_at::TIMESTAMP,
    order_delivered_carrier_date::TIMESTAMP,
    order_delivered_customer_date::TIMESTAMP,
    order_estimated_delivery_date::TIMESTAMP
FROM olist_orders_raw;

INSERT INTO olist_products
SELECT
    product_id,
    product_category_name,
    product_name_lenght::INTEGER,
    product_description_lenght::INTEGER,
    product_photos_qty::INTEGER,
    product_weight_g::INTEGER,
    product_length_cm::INTEGER,
    product_height_cm::INTEGER,
    product_width_cm::INTEGER
FROM olist_products_raw;

INSERT INTO olist_sellers
SELECT
    seller_id,
    seller_zip_code_prefix::INTEGER,
    seller_city,
    seller_state::CHAR(2)
FROM olist_sellers_raw;

INSERT INTO olist_order_items
SELECT
    order_id,
    order_item_id::INTEGER,
    product_id,
    seller_id,
    shipping_limit_date::TIMESTAMP,
    price::NUMERIC(12, 2),
    freight_value::NUMERIC(12, 2)
FROM olist_order_items_raw;
""")

======================================================================
Statement 1/5
======================================================================
INSERT INTO olist_customers
SELECT
    customer_id,
    customer_unique_id,
    customer_zip_code_prefix::INTEGER,
    customer_city,
    customer_state::CHAR(2)
FROM olist_customers_raw;
----------------------------------------------------------------------

Command executed successfully. Rows affected: 99441

======================================================================
Statement 2/5
======================================================================
INSERT INTO olist_orders
SELECT
    order_id,
    customer_id,
    order_status,
    order_purchase_timestamp::TIMESTAMP,
    order_approved_at::TIMESTAMP,
    order_delivered_carrier_date::TIMESTAMP,
    order_delivered_customer_date::TIMESTAMP,
    order_estimated_delivery_date::TIMESTAMP
FROM olist_orders_raw;
----------------------------------------------------------------------

Command executed successfully. Rows affected: 99441

======================================================================
Statement 3/5
======================================================================
INSERT INTO olist_products
SELECT
    product_id,
    product_category_name,
    product_name_lenght::INTEGER,
    product_description_lenght::INTEGER,
    product_photos_qty::INTEGER,
    product_weight_g::INTEGER,
    product_length_cm::INTEGER,
    product_height_cm::INTEGER,
    product_width_cm::INTEGER
FROM olist_products_raw;
----------------------------------------------------------------------
Command executed successfully. Rows affected: 32951

======================================================================
Statement 4/5
======================================================================
INSERT INTO olist_sellers
SELECT
    seller_id,
    seller_zip_code_prefix::INTEGER,
    seller_city,
    seller_state::CHAR(2)
FROM olist_sellers_raw;
----------------------------------------------------------------------
Command executed successfully. Rows affected: 3095

======================================================================
Statement 5/5
======================================================================
INSERT INTO olist_order_items
SELECT
    order_id,
    order_item_id::INTEGER,
    product_id,
    seller_id,
    shipping_limit_date::TIMESTAMP,
    price::NUMERIC(12, 2),
    freight_value::NUMERIC(12, 2)
FROM olist_order_items_raw;
----------------------------------------------------------------------

Command executed successfully. Rows affected: 112650

Finished successfully: 5 statement(s) executed.

In [7]:
execute_sql("""
SELECT 'customers' AS table_name, COUNT(*) AS n_rows FROM olist_customers
UNION ALL SELECT 'orders', COUNT(*) FROM olist_orders
UNION ALL SELECT 'order_items', COUNT(*) FROM olist_order_items
UNION ALL SELECT 'products', COUNT(*) FROM olist_products
UNION ALL SELECT 'sellers', COUNT(*) FROM olist_sellers
ORDER BY table_name;
""")

======================================================================
Statement 1/1
======================================================================
SELECT 'customers' AS table_name, COUNT(*) AS n_rows FROM olist_customers
UNION ALL SELECT 'orders', COUNT(*) FROM olist_orders
UNION ALL SELECT 'order_items', COUNT(*) FROM olist_order_items
UNION ALL SELECT 'products', COUNT(*) FROM olist_products
UNION ALL SELECT 'sellers', COUNT(*) FROM olist_sellers
ORDER BY table_name;
----------------------------------------------------------------------

    table_name  n_rows
0    customers   99441
1  order_items  112650
2       orders   99441
3     products   32951
4      sellers    3095

Finished successfully: 1 statement(s) executed.

Кількість рядків до і після перенесення однакова (за збереженими результатами запуску):

| Таблиця | Raw | Typed |
|---|---:|---:|
| customers | 99 441 | 99 441 |
| orders | 99 441 | 99 441 |
| order_items | 112 650 | 112 650 |
| products | 32 951 | 32 951 |
| sellers | 3 095 | 3 095 |

Під час перенесення в typed-таблиці жоден рядок не загубився, тож розбіжностей, які треба пояснювати, немає.

## 3. CTE-пайплайн ознак клієнтів

Пайплайн працює з typed-таблицями Olist. За `reference_date` беру наступний день після останнього замовлення в датасеті — так `recency_days` не залежить від того, коли саме запущено ноутбук. Кожен CTE-етап робить одну річ: окремо рахуються сума замовлення, RFM, квартал когорти, середній чек за 30 днів, частка скасувань і улюблена категорія.

In [8]:
execute_sql("""
WITH reference_date AS (
    -- Stage 0: stable reference date from the dataset

    SELECT
        MAX(order_purchase_timestamp)::DATE + 1 AS as_of_date
    FROM olist_orders
),
stage1_orders_total AS (
    -- Stage 1: one row and total value per order

    SELECT
        oo.customer_id,
        oo.order_id,
        oo.order_status,
        oo.order_purchase_timestamp,
        oo.order_purchase_timestamp::DATE AS order_date,
        SUM(
            COALESCE(oi.price, 0) +
            COALESCE(oi.freight_value, 0)
        )::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS oo
    LEFT JOIN olist_order_items AS oi
        ON oo.order_id = oi.order_id
    GROUP BY
        oo.customer_id,
        oo.order_id,
        oo.order_status,
        oo.order_purchase_timestamp
),

stage2_rmf AS (
    -- Stage 2: RFM features per customer

    SELECT
        ot.customer_id,
        (SELECT as_of_date FROM reference_date)
            - MAX(ot.order_date) AS recency_days,
        COUNT(DISTINCT ot.order_id) AS frequency,
        SUM(ot.order_total)::NUMERIC(12, 2) AS monetary,
        MIN(ot.order_purchase_timestamp)::DATE AS first_order_date
    FROM stage1_orders_total AS ot
    GROUP BY ot.customer_id
),

stage3_cohort AS (
    -- Stage 3: cohort quarter from the first order

    SELECT
        *,
        DATE_TRUNC('quarter', first_order_date)::DATE AS cohort_quarter
    FROM stage2_rmf
),

stage4_customer_30d_averages AS (
    -- Stage 4: rolling 30-day AOV for each customer's latest order
    SELECT
        customer_id,
        avg_order_value_30d
    FROM (
        SELECT
            ot.customer_id,
            AVG(ot.order_total) OVER (
                PARTITION BY ot.customer_id
                ORDER BY ot.order_purchase_timestamp
                RANGE BETWEEN INTERVAL '30 days' PRECEDING AND CURRENT ROW
            ) AS avg_order_value_30d,
            ROW_NUMBER() OVER (
                PARTITION BY ot.customer_id
                ORDER BY ot.order_purchase_timestamp DESC, ot.order_id DESC
            ) AS rn_recent
        FROM stage1_orders_total AS ot
    ) AS ranked
    WHERE rn_recent = 1
),

stage5_cancellation_rate AS (
    -- Stage 5: canceled-order share per customer

    SELECT
        customer_id,
        COUNT(
            CASE
                WHEN order_status = 'canceled' THEN 1
            END
        )::NUMERIC(12, 2) / COUNT(*) AS cancellation_rate
    FROM stage1_orders_total
    GROUP BY customer_id
),

stage6_customer_revenue_by_categories AS (
    -- Stage 6: revenue by customer and product category

    SELECT
        oo.customer_id,
        op.product_category_name,
        SUM(
            COALESCE(oi.price, 0) +
            COALESCE(oi.freight_value, 0)
        )::NUMERIC(12, 2) AS category_revenue
    FROM olist_orders AS oo
    LEFT JOIN olist_order_items AS oi
        ON oo.order_id = oi.order_id
    LEFT JOIN olist_products AS op
        ON oi.product_id = op.product_id
    GROUP BY
        oo.customer_id,
        op.product_category_name
),

stage7_preferred_categories AS (
    -- Stage 7: one highest-revenue category per customer; break ties by name
    SELECT
        customer_id,
        product_category_name AS preferred_category,
        category_revenue
    FROM (
        SELECT
            cr.*,
            ROW_NUMBER() OVER (
                PARTITION BY cr.customer_id
                ORDER BY cr.category_revenue DESC,
                         cr.product_category_name NULLS LAST
            ) AS rn
        FROM stage6_customer_revenue_by_categories AS cr
    ) AS ranked
    WHERE rn = 1
)

SELECT
    c.customer_id,
    c.customer_state,
    COALESCE(coh.recency_days, 9999) AS recency_days,
    COALESCE(coh.frequency, 0) AS frequency,
    COALESCE(coh.monetary, 0) AS monetary,
    coh.first_order_date,
    coh.cohort_quarter,
    COALESCE(avg.avg_order_value_30d, 0)::NUMERIC(12, 2)
        AS avg_order_value_30d_recent,
    COALESCE(can.cancellation_rate, 0)::NUMERIC(6, 4)
        AS cancellation_rate,
    COALESCE(pref.preferred_category, '(none)')
        AS preferred_category,
    COALESCE(pref.category_revenue, 0)::NUMERIC(12, 2)
        AS preferred_category_revenue
FROM olist_customers AS c
LEFT JOIN stage3_cohort AS coh
    ON c.customer_id = coh.customer_id
LEFT JOIN stage4_customer_30d_averages AS avg
    ON c.customer_id = avg.customer_id
LEFT JOIN stage5_cancellation_rate AS can
    ON c.customer_id = can.customer_id
LEFT JOIN stage7_preferred_categories AS pref
    ON c.customer_id = pref.customer_id
ORDER BY c.customer_id
LIMIT 20;
""")

======================================================================
Statement 1/1
======================================================================
WITH reference_date AS (
    -- Stage 0: stable reference date from the dataset

    SELECT
        MAX(order_purchase_timestamp)::DATE + 1 AS as_of_date
    FROM olist_orders
),
stage1_orders_total AS (
    -- Stage 1: one row and total value per order

    SELECT
        oo.customer_id,
        oo.order_id,
        oo.order_status,
        oo.order_purchase_timestamp,
        oo.order_purchase_timestamp::DATE AS order_date,
        SUM(
            COALESCE(oi.price, 0) +
            COALESCE(oi.freight_value, 0)
        )::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS oo
    LEFT JOIN olist_order_items AS oi
        ON oo.order_id = oi.order_id
    GROUP BY
        oo.customer_id,
        oo.order_id,
        oo.order_status,
        oo.order_purchase_timestamp
),

stage2_rmf AS (
    -- Stage 2: RFM features per customer

    SELECT
        ot.customer_id,
        (SELECT as_of_date FROM reference_date)
            - MAX(ot.order_date) AS recency_days,
        COUNT(DISTINCT ot.order_id) AS frequency,
        SUM(ot.order_total)::NUMERIC(12, 2) AS monetary,
        MIN(ot.order_purchase_timestamp)::DATE AS first_order_date
    FROM stage1_orders_total AS ot
    GROUP BY ot.customer_id
),

stage3_cohort AS (
    -- Stage 3: cohort quarter from the first order

    SELECT
        *,
        DATE_TRUNC('quarter', first_order_date)::DATE AS cohort_quarter
    FROM stage2_rmf
),

stage4_customer_30d_averages AS (
    -- Stage 4: rolling 30-day AOV for each customer's latest order
    SELECT
        customer_id,
        avg_order_value_30d
    FROM (
        SELECT
            ot.customer_id,
            AVG(ot.order_total) OVER (
                PARTITION BY ot.customer_id
                ORDER BY ot.order_purchase_timestamp
                RANGE BETWEEN INTERVAL '30 days' PRECEDING AND CURRENT ROW
            ) AS avg_order_value_30d,
            ROW_NUMBER() OVER (
                PARTITION BY ot.customer_id
                ORDER BY ot.order_purchase_timestamp DESC, ot.order_id DESC
            ) AS rn_recent
        FROM stage1_orders_total AS ot
    ) AS ranked
    WHERE rn_recent = 1
),

stage5_cancellation_rate AS (
    -- Stage 5: canceled-order share per customer

    SELECT
        customer_id,
        COUNT(
            CASE
                WHEN order_status = 'canceled' THEN 1
            END
        )::NUMERIC(12, 2) / COUNT(*) AS cancellation_rate
    FROM stage1_orders_total
    GROUP BY customer_id
),

stage6_customer_revenue_by_categories AS (
    -- Stage 6: revenue by customer and product category

    SELECT
        oo.customer_id,
        op.product_category_name,
        SUM(
            COALESCE(oi.price, 0) +
            COALESCE(oi.freight_value, 0)
        )::NUMERIC(12, 2) AS category_revenue
    FROM olist_orders AS oo
    LEFT JOIN olist_order_items AS oi
        ON oo.order_id = oi.order_id
    LEFT JOIN olist_products AS op
        ON oi.product_id = op.product_id
    GROUP BY
        oo.customer_id,
        op.product_category_name
),

stage7_preferred_categories AS (
    -- Stage 7: one highest-revenue category per customer; break ties by name
    SELECT
        customer_id,
        product_category_name AS preferred_category,
        category_revenue
    FROM (
        SELECT
            cr.*,
            ROW_NUMBER() OVER (
                PARTITION BY cr.customer_id
                ORDER BY cr.category_revenue DESC,
                         cr.product_category_name NULLS LAST
            ) AS rn
        FROM stage6_customer_revenue_by_categories AS cr
    ) AS ranked
    WHERE rn = 1
)

SELECT
    c.customer_id,
    c.customer_state,
    COALESCE(coh.recency_days, 9999) AS recency_days,
    COALESCE(coh.frequency, 0) AS frequency,
    COALESCE(coh.monetary, 0) AS monetary,
    coh.first_order_date,
    coh.cohort_quarter,
    COALESCE(avg.avg_order_value_30d, 0)::NUMERIC(12, 2)
        AS avg_order_value_30d_recent,
    COALESCE(can.cancellation_rate, 0)::NUMERIC(6, 4)
        AS cancellation_rate,
    COALESCE(pref.preferred_category, '(none)')
        AS preferred_category,
    COALESCE(pref.category_revenue, 0)::NUMERIC(12, 2)
        AS preferred_category_revenue
FROM olist_customers AS c
LEFT JOIN stage3_cohort AS coh
    ON c.customer_id = coh.customer_id
LEFT JOIN stage4_customer_30d_averages AS avg
    ON c.customer_id = avg.customer_id
LEFT JOIN stage5_cancellation_rate AS can
    ON c.customer_id = can.customer_id
LEFT JOIN stage7_preferred_categories AS pref
    ON c.customer_id = pref.customer_id
ORDER BY c.customer_id
LIMIT 20;
----------------------------------------------------------------------

,customer_id,customer_state,recency_days,frequency,monetary,first_order_date,cohort_quarter,avg_order_value_30d_recent,cancellation_rate,preferred_category,preferred_category_revenue
0,00012a2ce6f8dcda20d059ce98491703,SP,338,1,114.74,2017-11-14,2017-10-01,114.74,0.0000,brinquedos,114.74
1,000161a058600d5901f007fab4c27140,MG,459,1,67.41,2017-07-16,2017-07-01,67.41,0.0000,beleza_saude,67.41
2,0001fd6190edaaf884bcaf3d49edf079,ES,597,1,195.42,2017-02-28,2017-01-01,195.42,0.0000,bebes,195.42
3,0002414f95344307404f0ace7a26f1d5,MG,428,1,179.35,2017-08-16,2017-07-01,179.35,0.0000,cool_stuff,179.35
4,000379cdec625522490c315e70c7a9fb,SP,199,1,107.01,2018-04-02,2018-04-01,107.01,0.0000,cama_mesa_banho,107.01
5,0004164d20a9e969af783496f3408652,SP,554,1,71.80,2017-04-12,2017-04-01,71.80,0.0000,esporte_lazer,71.80
6,000419c5494106c306a97b5635748086,RJ,230,1,49.40,2018-03-02,2018-01-01,49.40,0.0000,fashion_bolsas_e_acessorios,49.40
7,00046a560d407e99b969756e0b10f282,RJ,304,1,166.59,2017-12-18,2017-10-01,166.59,0.0000,brinquedos,166.59
8,00050bf6e01e69d5c0fd612f1bcfb69c,RS,396,1,85.23,2017-09-17,2017-07-01,85.23,0.0000,fashion_bolsas_e_acessorios,85.23
9,000598caf2ef4117407665ac33275130,MG,68,1,1255.71,2018-08-11,2018-07-01,1255.71,0.0000,pet_shop,1255.71
10,0005aefbb696d34b3424dccd0a0e9fd0,SP,120,1,147.33,2018-06-20,2018-04-01,147.33,0.0000,cama_mesa_banho,147.33
11,00062b33cb9f6fe976afdcff967ea74d,SP,582,1,58.95,2017-03-15,2017-01-01,58.95,0.0000,beleza_saude,58.95
12,00066ccbe787a588c52bd5ff404590e3,RS,254,1,270.00,2018-02-06,2018-01-01,270.00,0.0000,ferramentas_jardim,270.00
13,00072d033fe2e59061ae5c3aff1a2be5,BA,412,1,106.97,2017-09-01,2017-07-01,106.97,0.0000,bebes,106.97
14,0009a69b72033b2d0ec8c69fc70ef768,SP,538,1,173.60,2017-04-28,2017-04-01,173.60,0.0000,ferramentas_jardim,173.60
15,000bf8121c3412d3057d32371c5d3395,SP,372,1,45.56,2017-10-11,2017-10-01,45.56,0.0000,moveis_decoracao,45.56
16,000e943451fc2788ca6ac98a682f2f49,RS,546,1,106.23,2017-04-20,2017-04-01,106.23,0.0000,cama_mesa_banho,106.23
17,000f17e290c26b28549908a04cfe36c1,RS,342,1,139.52,2017-11-10,2017-10-01,139.52,0.0000,esporte_lazer,139.52
18,000fd45d6fedae68fc6676036610f879,SP,186,1,66.81,2018-04-15,2018-04-01,66.81,0.0000,beleza_saude,66.81
19,0010068a73b7c56da5758c3f9e5c7375,CE,555,1,54.83,2017-04-11,2017-04-01,54.83,0.0000,telefonia,54.83

Finished successfully: 1 statement(s) executed.

## 4. Рекурсивний CTE: навчальний referral-граф

Реферальних зв'язків в Olist немає, тому таблицю `hw5_referrals` я заповнюю штучно. Anchor-частина через `NOT EXISTS` бере клієнтів, яких ніхто не запрошував, а рекурсивна на кожному кроці дописує запрошеного клієнта в `path` і збільшує `depth` на одиницю. Від циклів захищає перевірка, чи немає клієнта вже в `path`, а від надто довгих ланцюжків — умова `depth < 20`.

In [9]:
execute_sql("""
DROP TABLE IF EXISTS hw5_referrals CASCADE;

CREATE TABLE hw5_referrals (
    referrer_customer_id TEXT NOT NULL REFERENCES olist_customers(customer_id),
    referred_customer_id TEXT NOT NULL REFERENCES olist_customers(customer_id),
    referred_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (referred_customer_id),
    CHECK (referrer_customer_id <> referred_customer_id)
);

INSERT INTO hw5_referrals (referrer_customer_id, referred_customer_id)
SELECT
    (
        SELECT
            customer_id
        FROM olist_customers
        ORDER BY customer_id
        OFFSET rn.row_number
        LIMIT 1
    ) AS referrer_customer_id,
    (
        SELECT customer_id
        FROM olist_customers
        ORDER BY customer_id
        OFFSET rn.row_number + 1
        LIMIT 1
    ) AS referred_customer_id
FROM (SELECT generate_series(1, 10) as row_number) AS rn;


INSERT INTO hw5_referrals (referrer_customer_id, referred_customer_id)
SELECT
    (
        SELECT
            customer_id
        FROM olist_customers
        ORDER BY customer_id
        OFFSET rn.row_number + 10
        LIMIT 1
    ) AS referrer_customer_id,
    (
        SELECT customer_id
        FROM olist_customers
        ORDER BY customer_id
        OFFSET rn.row_number * 2 + 10
        LIMIT 1
    ) AS referred_customer_id
FROM (SELECT generate_series(1, 5) as row_number) AS rn;

SELECT *
FROM hw5_referrals
ORDER BY referrer_customer_id, referred_customer_id;
""")

======================================================================
Statement 1/5
======================================================================
DROP TABLE IF EXISTS hw5_referrals CASCADE;
----------------------------------------------------------------------
Command executed successfully.

======================================================================
Statement 2/5
======================================================================
CREATE TABLE hw5_referrals (
    referrer_customer_id TEXT NOT NULL REFERENCES olist_customers(customer_id),
    referred_customer_id TEXT NOT NULL REFERENCES olist_customers(customer_id),
    referred_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (referred_customer_id),
    CHECK (referrer_customer_id <> referred_customer_id)
);
----------------------------------------------------------------------
Command executed successfully.

======================================================================
Statement 3/5
======================================================================
INSERT INTO hw5_referrals (referrer_customer_id, referred_customer_id)
SELECT
    (
        SELECT
            customer_id
        FROM olist_customers
        ORDER BY customer_id
        OFFSET rn.row_number
        LIMIT 1
    ) AS referrer_customer_id,
    (
        SELECT customer_id
        FROM olist_customers
        ORDER BY customer_id
        OFFSET rn.row_number + 1
        LIMIT 1
    ) AS referred_customer_id
FROM (SELECT generate_series(1, 10) as row_number) AS rn;
----------------------------------------------------------------------
Command executed successfully. Rows affected: 10

======================================================================
Statement 4/5
======================================================================
INSERT INTO hw5_referrals (referrer_customer_id, referred_customer_id)
SELECT
    (
        SELECT
            customer_id
        FROM olist_customers
        ORDER BY customer_id
        OFFSET rn.row_number + 10
        LIMIT 1
    ) AS referrer_customer_id,
    (
        SELECT customer_id
        FROM olist_customers
        ORDER BY customer_id
        OFFSET rn.row_number * 2 + 10
        LIMIT 1
    ) AS referred_customer_id
FROM (SELECT generate_series(1, 5) as row_number) AS rn;
----------------------------------------------------------------------
Command executed successfully. Rows affected: 5

======================================================================
Statement 5/5
======================================================================
SELECT *
FROM hw5_referrals
ORDER BY referrer_customer_id, referred_customer_id;
----------------------------------------------------------------------

,referrer_customer_id,referred_customer_id,referred_at
0,000161a058600d5901f007fab4c27140,0001fd6190edaaf884bcaf3d49edf079,2026-10-06 00:11:26.450966+02:00
1,0001fd6190edaaf884bcaf3d49edf079,0002414f95344307404f0ace7a26f1d5,2026-10-06 00:11:26.450966+02:00
2,0002414f95344307404f0ace7a26f1d5,000379cdec625522490c315e70c7a9fb,2026-10-06 00:11:26.450966+02:00
3,000379cdec625522490c315e70c7a9fb,0004164d20a9e969af783496f3408652,2026-10-06 00:11:26.450966+02:00
4,0004164d20a9e969af783496f3408652,000419c5494106c306a97b5635748086,2026-10-06 00:11:26.450966+02:00
5,000419c5494106c306a97b5635748086,00046a560d407e99b969756e0b10f282,2026-10-06 00:11:26.450966+02:00
6,00046a560d407e99b969756e0b10f282,00050bf6e01e69d5c0fd612f1bcfb69c,2026-10-06 00:11:26.450966+02:00
7,00050bf6e01e69d5c0fd612f1bcfb69c,000598caf2ef4117407665ac33275130,2026-10-06 00:11:26.450966+02:00
8,000598caf2ef4117407665ac33275130,0005aefbb696d34b3424dccd0a0e9fd0,2026-10-06 00:11:26.450966+02:00
9,0005aefbb696d34b3424dccd0a0e9fd0,00062b33cb9f6fe976afdcff967ea74d,2026-10-06 00:11:26.450966+02:00
10,00062b33cb9f6fe976afdcff967ea74d,00066ccbe787a588c52bd5ff404590e3,2026-10-06 00:11:26.450966+02:00
11,00066ccbe787a588c52bd5ff404590e3,0009a69b72033b2d0ec8c69fc70ef768,2026-10-06 00:11:26.450966+02:00
12,00072d033fe2e59061ae5c3aff1a2be5,000e943451fc2788ca6ac98a682f2f49,2026-10-06 00:11:26.450966+02:00
13,0009a69b72033b2d0ec8c69fc70ef768,000fd45d6fedae68fc6676036610f879,2026-10-06 00:11:26.450966+02:00
14,000bf8121c3412d3057d32371c5d3395,001028b78fd413e19704b3867c369d3a,2026-10-06 00:11:26.450966+02:00

Finished successfully: 5 statement(s) executed.

In [10]:
execute_sql("""
WITH RECURSIVE referral_depth AS (
    SELECT
        1 AS depth,
        customer_id,
        ARRAY[customer_id] AS path
    FROM olist_customers
    WHERE NOT EXISTS (
        SELECT 1
        FROM hw5_referrals
        WHERE referred_customer_id = customer_id
    )

    UNION ALL

    SELECT
        rd.depth + 1 as depth,
        r.referred_customer_id AS customer_id,
        rd.path || r.referred_customer_id AS path
    FROM hw5_referrals AS r
    JOIN referral_depth AS rd
        ON r.referrer_customer_id = rd.customer_id
    WHERE r.referred_customer_id <> ALL(rd.path)
        AND rd.depth < 20
)
SELECT *
FROM referral_depth
WHERE depth >= 2
ORDER BY depth;
""")

======================================================================
Statement 1/1
======================================================================
WITH RECURSIVE referral_depth AS (
    SELECT
        1 AS depth,
        customer_id,
        ARRAY[customer_id] AS path
    FROM olist_customers
    WHERE NOT EXISTS (
        SELECT 1
        FROM hw5_referrals
        WHERE referred_customer_id = customer_id
    )

    UNION ALL

    SELECT
        rd.depth + 1 as depth,
        r.referred_customer_id AS customer_id,
        rd.path || r.referred_customer_id AS path
    FROM hw5_referrals AS r
    JOIN referral_depth AS rd
        ON r.referrer_customer_id = rd.customer_id
    WHERE r.referred_customer_id <> ALL(rd.path)
        AND rd.depth < 20
)
SELECT *
FROM referral_depth
WHERE depth >= 2
ORDER BY depth;
----------------------------------------------------------------------

,depth,customer_id,path
0,2,0001fd6190edaaf884bcaf3d49edf079,"[000161a058600d5901f007fab4c27140, 0001fd6190e..."
1,2,000e943451fc2788ca6ac98a682f2f49,"[00072d033fe2e59061ae5c3aff1a2be5, 000e943451f..."
2,2,001028b78fd413e19704b3867c369d3a,"[000bf8121c3412d3057d32371c5d3395, 001028b78fd..."
3,3,0002414f95344307404f0ace7a26f1d5,"[000161a058600d5901f007fab4c27140, 0001fd6190e..."
4,4,000379cdec625522490c315e70c7a9fb,"[000161a058600d5901f007fab4c27140, 0001fd6190e..."
5,5,0004164d20a9e969af783496f3408652,"[000161a058600d5901f007fab4c27140, 0001fd6190e..."
6,6,000419c5494106c306a97b5635748086,"[000161a058600d5901f007fab4c27140, 0001fd6190e..."
7,7,00046a560d407e99b969756e0b10f282,"[000161a058600d5901f007fab4c27140, 0001fd6190e..."
8,8,00050bf6e01e69d5c0fd612f1bcfb69c,"[000161a058600d5901f007fab4c27140, 0001fd6190e..."
9,9,000598caf2ef4117407665ac33275130,"[000161a058600d5901f007fab4c27140, 0001fd6190e..."
10,10,0005aefbb696d34b3424dccd0a0e9fd0,"[000161a058600d5901f007fab4c27140, 0001fd6190e..."
11,11,00062b33cb9f6fe976afdcff967ea74d,"[000161a058600d5901f007fab4c27140, 0001fd6190e..."
12,12,00066ccbe787a588c52bd5ff404590e3,"[000161a058600d5901f007fab4c27140, 0001fd6190e..."
13,13,0009a69b72033b2d0ec8c69fc70ef768,"[000161a058600d5901f007fab4c27140, 0001fd6190e..."
14,14,000fd45d6fedae68fc6676036610f879,"[000161a058600d5901f007fab4c27140, 0001fd6190e..."

Finished successfully: 1 statement(s) executed.

## 5. Materialized View

У MV зберігаються вже пораховані ознаки. Унікальний індекс на `customer_id` потрібен тому, що без нього `REFRESH MATERIALIZED VIEW CONCURRENTLY` не виконається. Після створення переглядаю вміст MV і окремою коміркою запускаю concurrent refresh. Варто пам'ятати, що дані в MV актуальні лише на момент останнього оновлення.

In [11]:
execute_sql("""
DROP MATERIALIZED VIEW IF EXISTS mv_olist_customer_features CASCADE;

CREATE MATERIALIZED VIEW mv_olist_customer_features AS
WITH reference_date AS (
    -- Stage 0: stable reference date from the dataset

    SELECT
        MAX(order_purchase_timestamp)::DATE + 1 AS as_of_date
    FROM olist_orders
),
stage1_orders_total AS (
    -- Stage 1: one row and total value per order

    SELECT
        oo.customer_id,
        oo.order_id,
        oo.order_status,
        oo.order_purchase_timestamp,
        oo.order_purchase_timestamp::DATE AS order_date,
        SUM(
            COALESCE(oi.price, 0) +
            COALESCE(oi.freight_value, 0)
        )::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS oo
    LEFT JOIN olist_order_items AS oi
        ON oo.order_id = oi.order_id
    GROUP BY
        oo.customer_id,
        oo.order_id,
        oo.order_status,
        oo.order_purchase_timestamp
),

stage2_rmf AS (
    -- Stage 2: RFM features per customer

    SELECT
        ot.customer_id,
        (SELECT as_of_date FROM reference_date)
            - MAX(ot.order_date) AS recency_days,
        COUNT(DISTINCT ot.order_id) AS frequency,
        SUM(ot.order_total)::NUMERIC(12, 2) AS monetary,
        MIN(ot.order_purchase_timestamp)::DATE AS first_order_date
    FROM stage1_orders_total AS ot
    GROUP BY ot.customer_id
),

stage3_cohort AS (
    -- Stage 3: cohort quarter from the first order

    SELECT
        *,
        DATE_TRUNC('quarter', first_order_date)::DATE AS cohort_quarter
    FROM stage2_rmf
),

stage4_customer_30d_averages AS (
    -- Stage 4: rolling 30-day AOV for each customer's latest order
    SELECT
        customer_id,
        avg_order_value_30d
    FROM (
        SELECT
            ot.customer_id,
            AVG(ot.order_total) OVER (
                PARTITION BY ot.customer_id
                ORDER BY ot.order_purchase_timestamp
                RANGE BETWEEN INTERVAL '30 days' PRECEDING AND CURRENT ROW
            ) AS avg_order_value_30d,
            ROW_NUMBER() OVER (
                PARTITION BY ot.customer_id
                ORDER BY ot.order_purchase_timestamp DESC, ot.order_id DESC
            ) AS rn_recent
        FROM stage1_orders_total AS ot
    ) AS ranked
    WHERE rn_recent = 1
),

stage5_cancellation_rate AS (
    -- Stage 5: canceled-order share per customer

    SELECT
        customer_id,
        COUNT(
            CASE
                WHEN order_status = 'canceled' THEN 1
            END
        )::NUMERIC(12, 2) / COUNT(*) AS cancellation_rate
    FROM stage1_orders_total
    GROUP BY customer_id
),

stage6_customer_revenue_by_categories AS (
    -- Stage 6: revenue by customer and product category

    SELECT
        oo.customer_id,
        op.product_category_name,
        SUM(
            COALESCE(oi.price, 0) +
            COALESCE(oi.freight_value, 0)
        )::NUMERIC(12, 2) AS category_revenue
    FROM olist_orders AS oo
    LEFT JOIN olist_order_items AS oi
        ON oo.order_id = oi.order_id
    LEFT JOIN olist_products AS op
        ON oi.product_id = op.product_id
    GROUP BY
        oo.customer_id,
        op.product_category_name
),

stage7_preferred_categories AS (
    -- Stage 7: one highest-revenue category per customer; break ties by name
    SELECT
        customer_id,
        product_category_name AS preferred_category,
        category_revenue
    FROM (
        SELECT
            cr.*,
            ROW_NUMBER() OVER (
                PARTITION BY cr.customer_id
                ORDER BY cr.category_revenue DESC,
                         cr.product_category_name NULLS LAST
            ) AS rn
        FROM stage6_customer_revenue_by_categories AS cr
    ) AS ranked
    WHERE rn = 1
)

SELECT
    c.customer_id,
    c.customer_state,
    COALESCE(coh.recency_days, 9999) AS recency_days,
    COALESCE(coh.frequency, 0) AS frequency,
    COALESCE(coh.monetary, 0) AS monetary,
    coh.first_order_date,
    coh.cohort_quarter,
    COALESCE(avg.avg_order_value_30d, 0)::NUMERIC(12, 2)
        AS avg_order_value_30d_recent,
    COALESCE(can.cancellation_rate, 0)::NUMERIC(6, 4)
        AS cancellation_rate,
    COALESCE(pref.preferred_category, '(none)')
        AS preferred_category,
    COALESCE(pref.category_revenue, 0)::NUMERIC(12, 2)
        AS preferred_category_revenue
FROM olist_customers AS c
LEFT JOIN stage3_cohort AS coh
    ON c.customer_id = coh.customer_id
LEFT JOIN stage4_customer_30d_averages AS avg
    ON c.customer_id = avg.customer_id
LEFT JOIN stage5_cancellation_rate AS can
    ON c.customer_id = can.customer_id
LEFT JOIN stage7_preferred_categories AS pref
    ON c.customer_id = pref.customer_id;

CREATE UNIQUE INDEX idx_mv_olist_customer_features_customer_id
    ON mv_olist_customer_features(customer_id);
""")

======================================================================
Statement 1/3
======================================================================
DROP MATERIALIZED VIEW IF EXISTS mv_olist_customer_features CASCADE;
----------------------------------------------------------------------
Command executed successfully.

======================================================================
Statement 2/3
======================================================================
CREATE MATERIALIZED VIEW mv_olist_customer_features AS
WITH reference_date AS (
    -- Stage 0: stable reference date from the dataset

    SELECT
        MAX(order_purchase_timestamp)::DATE + 1 AS as_of_date
    FROM olist_orders
),
stage1_orders_total AS (
    -- Stage 1: one row and total value per order

    SELECT
        oo.customer_id,
        oo.order_id,
        oo.order_status,
        oo.order_purchase_timestamp,
        oo.order_purchase_timestamp::DATE AS order_date,
        SUM(
            COALESCE(oi.price, 0) +
            COALESCE(oi.freight_value, 0)
        )::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS oo
    LEFT JOIN olist_order_items AS oi
        ON oo.order_id = oi.order_id
    GROUP BY
        oo.customer_id,
        oo.order_id,
        oo.order_status,
        oo.order_purchase_timestamp
),

stage2_rmf AS (
    -- Stage 2: RFM features per customer

    SELECT
        ot.customer_id,
        (SELECT as_of_date FROM reference_date)
            - MAX(ot.order_date) AS recency_days,
        COUNT(DISTINCT ot.order_id) AS frequency,
        SUM(ot.order_total)::NUMERIC(12, 2) AS monetary,
        MIN(ot.order_purchase_timestamp)::DATE AS first_order_date
    FROM stage1_orders_total AS ot
    GROUP BY ot.customer_id
),

stage3_cohort AS (
    -- Stage 3: cohort quarter from the first order

    SELECT
        *,
        DATE_TRUNC('quarter', first_order_date)::DATE AS cohort_quarter
    FROM stage2_rmf
),

stage4_customer_30d_averages AS (
    -- Stage 4: rolling 30-day AOV for each customer's latest order
    SELECT
        customer_id,
        avg_order_value_30d
    FROM (
        SELECT
            ot.customer_id,
            AVG(ot.order_total) OVER (
                PARTITION BY ot.customer_id
                ORDER BY ot.order_purchase_timestamp
                RANGE BETWEEN INTERVAL '30 days' PRECEDING AND CURRENT ROW
            ) AS avg_order_value_30d,
            ROW_NUMBER() OVER (
                PARTITION BY ot.customer_id
                ORDER BY ot.order_purchase_timestamp DESC, ot.order_id DESC
            ) AS rn_recent
        FROM stage1_orders_total AS ot
    ) AS ranked
    WHERE rn_recent = 1
),

stage5_cancellation_rate AS (
    -- Stage 5: canceled-order share per customer

    SELECT
        customer_id,
        COUNT(
            CASE
                WHEN order_status = 'canceled' THEN 1
            END
        )::NUMERIC(12, 2) / COUNT(*) AS cancellation_rate
    FROM stage1_orders_total
    GROUP BY customer_id
),

stage6_customer_revenue_by_categories AS (
    -- Stage 6: revenue by customer and product category

    SELECT
        oo.customer_id,
        op.product_category_name,
        SUM(
            COALESCE(oi.price, 0) +
            COALESCE(oi.freight_value, 0)
        )::NUMERIC(12, 2) AS category_revenue
    FROM olist_orders AS oo
    LEFT JOIN olist_order_items AS oi
        ON oo.order_id = oi.order_id
    LEFT JOIN olist_products AS op
        ON oi.product_id = op.product_id
    GROUP BY
        oo.customer_id,
        op.product_category_name
),

stage7_preferred_categories AS (
    -- Stage 7: one highest-revenue category per customer; break ties by name
    SELECT
        customer_id,
        product_category_name AS preferred_category,
        category_revenue
    FROM (
        SELECT
            cr.*,
            ROW_NUMBER() OVER (
                PARTITION BY cr.customer_id
                ORDER BY cr.category_revenue DESC,
                         cr.product_category_name NULLS LAST
            ) AS rn
        FROM stage6_customer_revenue_by_categories AS cr
    ) AS ranked
    WHERE rn = 1
)

SELECT
    c.customer_id,
    c.customer_state,
    COALESCE(coh.recency_days, 9999) AS recency_days,
    COALESCE(coh.frequency, 0) AS frequency,
    COALESCE(coh.monetary, 0) AS monetary,
    coh.first_order_date,
    coh.cohort_quarter,
    COALESCE(avg.avg_order_value_30d, 0)::NUMERIC(12, 2)
        AS avg_order_value_30d_recent,
    COALESCE(can.cancellation_rate, 0)::NUMERIC(6, 4)
        AS cancellation_rate,
    COALESCE(pref.preferred_category, '(none)')
        AS preferred_category,
    COALESCE(pref.category_revenue, 0)::NUMERIC(12, 2)
        AS preferred_category_revenue
FROM olist_customers AS c
LEFT JOIN stage3_cohort AS coh
    ON c.customer_id = coh.customer_id
LEFT JOIN stage4_customer_30d_averages AS avg
    ON c.customer_id = avg.customer_id
LEFT JOIN stage5_cancellation_rate AS can
    ON c.customer_id = can.customer_id
LEFT JOIN stage7_preferred_categories AS pref
    ON c.customer_id = pref.customer_id;
----------------------------------------------------------------------

Command executed successfully. Rows affected: 99441

======================================================================
Statement 3/3
======================================================================
CREATE UNIQUE INDEX idx_mv_olist_customer_features_customer_id
    ON mv_olist_customer_features(customer_id);
----------------------------------------------------------------------
Command executed successfully.

Finished successfully: 3 statement(s) executed.

In [12]:
execute_sql("""
SELECT COUNT(*) AS n_rows
FROM mv_olist_customer_features;

SELECT *
FROM mv_olist_customer_features
ORDER BY monetary DESC NULLS LAST, customer_id
LIMIT 5;
""")

======================================================================
Statement 1/2
======================================================================
SELECT COUNT(*) AS n_rows
FROM mv_olist_customer_features;
----------------------------------------------------------------------

   n_rows
0   99441

======================================================================
Statement 2/2
======================================================================
SELECT *
FROM mv_olist_customer_features
ORDER BY monetary DESC NULLS LAST, customer_id
LIMIT 5;
----------------------------------------------------------------------

,customer_id,customer_state,recency_days,frequency,monetary,first_order_date,cohort_quarter,avg_order_value_30d_recent,cancellation_rate,preferred_category,preferred_category_revenue
0,1617b1357756262bfa56ab541c47bc16,RJ,384,1,13664.08,2017-09-29,2017-07-01,13664.08,0.0000,telefonia_fixa,13664.08
1,ec5b2ba62e574342386871631fafd3fc,ES,95,1,7274.88,2018-07-15,2018-07-01,7274.88,0.0000,telefonia_fixa,7274.88
2,c6e2731c5b391845f6800c97401a43a9,MS,613,1,6929.31,2017-02-12,2017-01-01,6929.31,0.0000,utilidades_domesticas,6929.31
3,f48d464a0baaea338cb25f816991ab1f,ES,85,1,6922.21,2018-07-25,2018-07-01,6922.21,0.0000,pcs,6922.21
4,3fd6777bbce08a352fddd04e4a7cc8f6,SP,512,1,6726.66,2017-05-24,2017-04-01,6726.66,0.0000,artes,6726.66

Finished successfully: 2 statement(s) executed.

In [13]:
execute_sql("""
REFRESH MATERIALIZED VIEW CONCURRENTLY mv_olist_customer_features;
""")

======================================================================
Statement 1/1
======================================================================
REFRESH MATERIALIZED VIEW CONCURRENTLY mv_olist_customer_features;
----------------------------------------------------------------------

Command executed successfully.

Finished successfully: 1 statement(s) executed.

## 6. Плани виконання

Нижче збережено `EXPLAIN (ANALYZE, BUFFERS)` для переобчислення CTE-пайплайна і для читання з MV. Абсолютний час залежить від середовища, кешу та обсягу даних, тому при порівнянні важливіше дивитися, які операції з'являються в плані, і зважати на те, що саме лежить у MV.

In [14]:
res = execute_sql("""
EXPLAIN (ANALYZE, BUFFERS)
WITH reference_date AS (
    -- Stage 0: stable reference date from the dataset

    SELECT
        MAX(order_purchase_timestamp)::DATE + 1 AS as_of_date
    FROM olist_orders
),
stage1_orders_total AS (
    -- Stage 1: one row and total value per order

    SELECT
        oo.customer_id,
        oo.order_id,
        oo.order_status,
        oo.order_purchase_timestamp,
        oo.order_purchase_timestamp::DATE AS order_date,
        SUM(
            COALESCE(oi.price, 0) +
            COALESCE(oi.freight_value, 0)
        )::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS oo
    LEFT JOIN olist_order_items AS oi
        ON oo.order_id = oi.order_id
    GROUP BY
        oo.customer_id,
        oo.order_id,
        oo.order_status,
        oo.order_purchase_timestamp
),

stage2_rmf AS (
    -- Stage 2: RFM features per customer

    SELECT
        ot.customer_id,
        (SELECT as_of_date FROM reference_date)
            - MAX(ot.order_date) AS recency_days,
        COUNT(DISTINCT ot.order_id) AS frequency,
        SUM(ot.order_total)::NUMERIC(12, 2) AS monetary,
        MIN(ot.order_purchase_timestamp)::DATE AS first_order_date
    FROM stage1_orders_total AS ot
    GROUP BY ot.customer_id
),

stage3_cohort AS (
    -- Stage 3: cohort quarter from the first order

    SELECT
        *,
        DATE_TRUNC('quarter', first_order_date)::DATE AS cohort_quarter
    FROM stage2_rmf
),

stage4_customer_30d_averages AS (
    -- Stage 4: rolling 30-day AOV for each customer's latest order
    SELECT
        customer_id,
        avg_order_value_30d
    FROM (
        SELECT
            ot.customer_id,
            AVG(ot.order_total) OVER (
                PARTITION BY ot.customer_id
                ORDER BY ot.order_purchase_timestamp
                RANGE BETWEEN INTERVAL '30 days' PRECEDING AND CURRENT ROW
            ) AS avg_order_value_30d,
            ROW_NUMBER() OVER (
                PARTITION BY ot.customer_id
                ORDER BY ot.order_purchase_timestamp DESC, ot.order_id DESC
            ) AS rn_recent
        FROM stage1_orders_total AS ot
    ) AS ranked
    WHERE rn_recent = 1
),

stage5_cancellation_rate AS (
    -- Stage 5: canceled-order share per customer

    SELECT
        customer_id,
        COUNT(
            CASE
                WHEN order_status = 'canceled' THEN 1
            END
        )::NUMERIC(12, 2) / COUNT(*) AS cancellation_rate
    FROM stage1_orders_total
    GROUP BY customer_id
),

stage6_customer_revenue_by_categories AS (
    -- Stage 6: revenue by customer and product category

    SELECT
        oo.customer_id,
        op.product_category_name,
        SUM(
            COALESCE(oi.price, 0) +
            COALESCE(oi.freight_value, 0)
        )::NUMERIC(12, 2) AS category_revenue
    FROM olist_orders AS oo
    LEFT JOIN olist_order_items AS oi
        ON oo.order_id = oi.order_id
    LEFT JOIN olist_products AS op
        ON oi.product_id = op.product_id
    GROUP BY
        oo.customer_id,
        op.product_category_name
),

stage7_preferred_categories AS (
    -- Stage 7: one highest-revenue category per customer; break ties by name
    SELECT
        customer_id,
        product_category_name AS preferred_category,
        category_revenue
    FROM (
        SELECT
            cr.*,
            ROW_NUMBER() OVER (
                PARTITION BY cr.customer_id
                ORDER BY cr.category_revenue DESC,
                         cr.product_category_name NULLS LAST
            ) AS rn
        FROM stage6_customer_revenue_by_categories AS cr
    ) AS ranked
    WHERE rn = 1
)

SELECT
    c.customer_id,
    c.customer_state,
    COALESCE(coh.recency_days, 9999) AS recency_days,
    COALESCE(coh.frequency, 0) AS frequency,
    COALESCE(coh.monetary, 0) AS monetary,
    coh.first_order_date,
    coh.cohort_quarter,
    COALESCE(avg.avg_order_value_30d, 0)::NUMERIC(12, 2)
        AS avg_order_value_30d_recent,
    COALESCE(can.cancellation_rate, 0)::NUMERIC(6, 4)
        AS cancellation_rate,
    COALESCE(pref.preferred_category, '(none)')
        AS preferred_category,
    COALESCE(pref.category_revenue, 0)::NUMERIC(12, 2)
        AS preferred_category_revenue
FROM olist_customers AS c
LEFT JOIN stage3_cohort AS coh
    ON c.customer_id = coh.customer_id
LEFT JOIN stage4_customer_30d_averages AS avg
    ON c.customer_id = avg.customer_id
LEFT JOIN stage5_cancellation_rate AS can
    ON c.customer_id = can.customer_id
LEFT JOIN stage7_preferred_categories AS pref
    ON c.customer_id = pref.customer_id
ORDER BY c.customer_id
LIMIT 20;
""", return_result=True)

print(res)

for row in res[0]['data'].itertuples(index=True, name='Row'):
    print(row)

======================================================================
Statement 1/1
======================================================================
EXPLAIN (ANALYZE, BUFFERS)
WITH reference_date AS (
    -- Stage 0: stable reference date from the dataset

    SELECT
        MAX(order_purchase_timestamp)::DATE + 1 AS as_of_date
    FROM olist_orders
),
stage1_orders_total AS (
    -- Stage 1: one row and total value per order

    SELECT
        oo.customer_id,
        oo.order_id,
        oo.order_status,
        oo.order_purchase_timestamp,
        oo.order_purchase_timestamp::DATE AS order_date,
        SUM(
            COALESCE(oi.price, 0) +
            COALESCE(oi.freight_value, 0)
        )::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS oo
    LEFT JOIN olist_order_items AS oi
        ON oo.order_id = oi.order_id
    GROUP BY
        oo.customer_id,
        oo.order_id,
        oo.order_status,
        oo.order_purchase_timestamp
),

stage2_rmf AS (
    -- Stage 2: RFM features per customer

    SELECT
        ot.customer_id,
        (SELECT as_of_date FROM reference_date)
            - MAX(ot.order_date) AS recency_days,
        COUNT(DISTINCT ot.order_id) AS frequency,
        SUM(ot.order_total)::NUMERIC(12, 2) AS monetary,
        MIN(ot.order_purchase_timestamp)::DATE AS first_order_date
    FROM stage1_orders_total AS ot
    GROUP BY ot.customer_id
),

stage3_cohort AS (
    -- Stage 3: cohort quarter from the first order

    SELECT
        *,
        DATE_TRUNC('quarter', first_order_date)::DATE AS cohort_quarter
    FROM stage2_rmf
),

stage4_customer_30d_averages AS (
    -- Stage 4: rolling 30-day AOV for each customer's latest order
    SELECT
        customer_id,
        avg_order_value_30d
    FROM (
        SELECT
            ot.customer_id,
            AVG(ot.order_total) OVER (
                PARTITION BY ot.customer_id
                ORDER BY ot.order_purchase_timestamp
                RANGE BETWEEN INTERVAL '30 days' PRECEDING AND CURRENT ROW
            ) AS avg_order_value_30d,
            ROW_NUMBER() OVER (
                PARTITION BY ot.customer_id
                ORDER BY ot.order_purchase_timestamp DESC, ot.order_id DESC
            ) AS rn_recent
        FROM stage1_orders_total AS ot
    ) AS ranked
    WHERE rn_recent = 1
),

stage5_cancellation_rate AS (
    -- Stage 5: canceled-order share per customer

    SELECT
        customer_id,
        COUNT(
            CASE
                WHEN order_status = 'canceled' THEN 1
            END
        )::NUMERIC(12, 2) / COUNT(*) AS cancellation_rate
    FROM stage1_orders_total
    GROUP BY customer_id
),

stage6_customer_revenue_by_categories AS (
    -- Stage 6: revenue by customer and product category

    SELECT
        oo.customer_id,
        op.product_category_name,
        SUM(
            COALESCE(oi.price, 0) +
            COALESCE(oi.freight_value, 0)
        )::NUMERIC(12, 2) AS category_revenue
    FROM olist_orders AS oo
    LEFT JOIN olist_order_items AS oi
        ON oo.order_id = oi.order_id
    LEFT JOIN olist_products AS op
        ON oi.product_id = op.product_id
    GROUP BY
        oo.customer_id,
        op.product_category_name
),

stage7_preferred_categories AS (
    -- Stage 7: one highest-revenue category per customer; break ties by name
    SELECT
        customer_id,
        product_category_name AS preferred_category,
        category_revenue
    FROM (
        SELECT
            cr.*,
            ROW_NUMBER() OVER (
                PARTITION BY cr.customer_id
                ORDER BY cr.category_revenue DESC,
                         cr.product_category_name NULLS LAST
            ) AS rn
        FROM stage6_customer_revenue_by_categories AS cr
    ) AS ranked
    WHERE rn = 1
)

SELECT
    c.customer_id,
    c.customer_state,
    COALESCE(coh.recency_days, 9999) AS recency_days,
    COALESCE(coh.frequency, 0) AS frequency,
    COALESCE(coh.monetary, 0) AS monetary,
    coh.first_order_date,
    coh.cohort_quarter,
    COALESCE(avg.avg_order_value_30d, 0)::NUMERIC(12, 2)
        AS avg_order_value_30d_recent,
    COALESCE(can.cancellation_rate, 0)::NUMERIC(6, 4)
        AS cancellation_rate,
    COALESCE(pref.preferred_category, '(none)')
        AS preferred_category,
    COALESCE(pref.category_revenue, 0)::NUMERIC(12, 2)
        AS preferred_category_revenue
FROM olist_customers AS c
LEFT JOIN stage3_cohort AS coh
    ON c.customer_id = coh.customer_id
LEFT JOIN stage4_customer_30d_averages AS avg
    ON c.customer_id = avg.customer_id
LEFT JOIN stage5_cancellation_rate AS can
    ON c.customer_id = can.customer_id
LEFT JOIN stage7_preferred_categories AS pref
    ON c.customer_id = pref.customer_id
ORDER BY c.customer_id
LIMIT 20;
----------------------------------------------------------------------

                                            QUERY PLAN
0    Limit  (cost=76965.36..76973.31 rows=20 width=...
1      Buffers: shared hit=11021, temp read=6713 wr...
2                              CTE stage1_orders_total
3        ->  Finalize GroupAggregate  (cost=16725.6...
4                             Group Key: oo_1.order_id
..                                                 ...
137                                                ...
138                                          Planning:
139                              Buffers: shared hit=2
140                            Planning Time: 0.658 ms
141                         Execution Time: 635.124 ms

[142 rows x 1 columns]

Finished successfully: 1 statement(s) executed.
[{'statement_number': 1, 'statement': "EXPLAIN (ANALYZE, BUFFERS)\nWITH reference_date AS (\n    -- Stage 0: stable reference date from the dataset\n\n    SELECT\n        MAX(order_purchase_timestamp)::DATE + 1 AS as_of_date\n    FROM olist_orders\n),\nstage1_orders_total AS (\n    -- Stage 1: one row and total value per order\n\n    SELECT\n        oo.customer_id,\n        oo.order_id,\n        oo.order_status,\n        oo.order_purchase_timestamp,\n        oo.order_purchase_timestamp::DATE AS order_date,\n        SUM(\n            COALESCE(oi.price, 0) +\n            COALESCE(oi.freight_value, 0)\n        )::NUMERIC(12, 2) AS order_total\n    FROM olist_orders AS oo\n    LEFT JOIN olist_order_items AS oi\n        ON oo.order_id = oi.order_id\n    GROUP BY\n        oo.customer_id,\n        oo.order_id,\n        oo.order_status,\n        oo.order_purchase_timestamp\n),\n\nstage2_rmf AS (\n    -- Stage 2: RFM features per customer\n\n    SELECT\n        ot.customer_id,\n        (SELECT as_of_date FROM reference_date)\n            - MAX(ot.order_date) AS recency_days,\n        COUNT(DISTINCT ot.order_id) AS frequency,\n        SUM(ot.order_total)::NUMERIC(12, 2) AS monetary,\n        MIN(ot.order_purchase_timestamp)::DATE AS first_order_date\n    FROM stage1_orders_total AS ot\n    GROUP BY ot.customer_id\n),\n\nstage3_cohort AS (\n    -- Stage 3: cohort quarter from the first order\n\n    SELECT\n        *,\n        DATE_TRUNC('quarter', first_order_date)::DATE AS cohort_quarter\n    FROM stage2_rmf\n),\n\nstage4_customer_30d_averages AS (\n    -- Stage 4: rolling 30-day AOV for each customer's latest order\n    SELECT\n        customer_id,\n        avg_order_value_30d\n    FROM (\n        SELECT\n            ot.customer_id,\n            AVG(ot.order_total) OVER (\n                PARTITION BY ot.customer_id\n                ORDER BY ot.order_purchase_timestamp\n                RANGE BETWEEN INTERVAL '30 days' PRECEDING AND CURRENT ROW\n            ) AS avg_order_value_30d,\n            ROW_NUMBER() OVER (\n                PARTITION BY ot.customer_id\n                ORDER BY ot.order_purchase_timestamp DESC, ot.order_id DESC\n            ) AS rn_recent\n        FROM stage1_orders_total AS ot\n    ) AS ranked\n    WHERE rn_recent = 1\n),\n\nstage5_cancellation_rate AS (\n    -- Stage 5: canceled-order share per customer\n\n    SELECT\n        customer_id,\n        COUNT(\n            CASE\n                WHEN order_status = 'canceled' THEN 1\n            END\n        )::NUMERIC(12, 2) / COUNT(*) AS cancellation_rate\n    FROM stage1_orders_total\n    GROUP BY customer_id\n),\n\nstage6_customer_revenue_by_categories AS (\n    -- Stage 6: revenue by customer and product category\n\n    SELECT\n        oo.customer_id,\n        op.product_category_name,\n        SUM(\n            COALESCE(oi.price, 0) +\n            COALESCE(oi.freight_value, 0)\n        )::NUMERIC(12, 2) AS category_revenue\n    FROM olist_orders AS oo\n    LEFT JOIN olist_order_items AS oi\n        ON oo.order_id = oi.order_id\n    LEFT JOIN olist_products AS op\n        ON oi.product_id = op.product_id\n    GROUP BY\n        oo.customer_id,\n        op.product_category_name\n),\n\nstage7_preferred_categories AS (\n    -- Stage 7: one highest-revenue category per customer; break ties by name\n    SELECT\n        customer_id,\n        product_category_name AS preferred_category,\n        category_revenue\n    FROM (\n        SELECT\n            cr.*,\n            ROW_NUMBER() OVER (\n                PARTITION BY cr.customer_id\n                ORDER BY cr.category_revenue DESC,\n                         cr.product_category_name NULLS LAST\n            ) AS rn\n        FROM stage6_customer_revenue_by_categories AS cr\n    ) AS ranked\n    WHERE rn = 1\n)\n\nSELECT\n    c.customer_id,\n    c.customer_state,\n    COALESCE(coh.recency_days, 9999) AS recency_days,\n    COALESCE(coh.frequency, 0) AS frequency,\n    COALESCE(coh.monetary, 0) AS monetary,\n    coh.first_order_date,\n    coh.cohort_quarter,\n    COALESCE(avg.avg_order_value_30d, 0)::NUMERIC(12, 2)\n        AS avg_order_value_30d_recent,\n    COALESCE(can.cancellation_rate, 0)::NUMERIC(6, 4)\n        AS cancellation_rate,\n    COALESCE(pref.preferred_category, '(none)')\n        AS preferred_category,\n    COALESCE(pref.category_revenue, 0)::NUMERIC(12, 2)\n        AS preferred_category_revenue\nFROM olist_customers AS c\nLEFT JOIN stage3_cohort AS coh\n    ON c.customer_id = coh.customer_id\nLEFT JOIN stage4_customer_30d_averages AS avg\n    ON c.customer_id = avg.customer_id\nLEFT JOIN stage5_cancellation_rate AS can\n    ON c.customer_id = can.customer_id\nLEFT JOIN stage7_preferred_categories AS pref\n    ON c.customer_id = pref.customer_id\nORDER BY c.customer_id\nLIMIT 20;", 'type': 'result_set', 'data':                                             QUERY PLAN
0    Limit  (cost=76965.36..76973.31 rows=20 width=...
1      Buffers: shared hit=11021, temp read=6713 wr...
2                              CTE stage1_orders_total
3        ->  Finalize GroupAggregate  (cost=16725.6...
4                             Group Key: oo_1.order_id
..                                                 ...
137                                                ...
138                                          Planning:
139                              Buffers: shared hit=2
140                            Planning Time: 0.658 ms
141                         Execution Time: 635.124 ms

[142 rows x 1 columns]}]
Row(Index=0, _1='Limit  (cost=76965.36..76973.31 rows=20 width=174) (actual time=622.365..629.245 rows=20 loops=1)')
Row(Index=1, _1='  Buffers: shared hit=11021, temp read=6713 written=7541')
Row(Index=2, _1='  CTE stage1_orders_total')
Row(Index=3, _1='    ->  Finalize GroupAggregate  (cost=16725.66..27526.12 rows=88592 width=124) (actual time=66.209..180.760 rows=99441 loops=1)')
Row(Index=4, _1='          Group Key: oo_1.order_id')
Row(Index=5, _1='          Buffers: shared hit=4158, temp read=1545 written=1549')
Row(Index=6, _1='          ->  Gather Merge  (cost=16725.66..25488.91 rows=64913 width=136) (actual time=66.199..127.858 rows=99637 loops=1)')
Row(Index=7, _1='                Workers Planned: 1')
Row(Index=8, _1='                Workers Launched: 1')
Row(Index=9, _1='                Buffers: shared hit=4158, temp read=1545 written=1549')
Row(Index=10, _1='                ->  Partial GroupAggregate  (cost=15725.65..17186.19 rows=64913 width=136) (actual time=60.995..99.123 rows=49818 loops=2)')
Row(Index=11, _1='                      Group Key: oo_1.order_id')
Row(Index=12, _1='                      Buffers: shared hit=4158, temp read=1545 written=1549')
Row(Index=13, _1='                      ->  Sort  (cost=15725.65..15887.93 rows=64913 width=136) (actual time=60.982..67.995 rows=56712 loops=2)')
Row(Index=14, _1='                            Sort Key: oo_1.order_id')
Row(Index=15, _1='                            Sort Method: external merge  Disk: 6368kB')
Row(Index=16, _1='                            Buffers: shared hit=4158, temp read=1545 written=1549')
Row(Index=17, _1='                            Worker 0:  Sort Method: external merge  Disk: 5992kB')
Row(Index=18, _1='                            ->  Parallel Hash Right Join  (cost=2980.54..6099.08 rows=64913 width=136) (actual time=19.774..46.854 rows=56712 loops=2)')
Row(Index=19, _1='                                  Hash Cond: (oi_1.order_id = oo_1.order_id)')
Row(Index=20, _1='                                  Buffers: shared hit=4121')
Row(Index=21, _1='                                  ->  Parallel Seq Scan on olist_order_items oi_1  (cost=0.00..2948.13 rows=64913 width=64) (actual time=0.007..4.168 rows=56325 loops=2)')
Row(Index=22, _1='                                        Buffers: shared hit=2299')
Row(Index=23, _1='                                  ->  Parallel Hash  (cost=2329.13..2329.13 rows=52113 width=104) (actual time=18.964..18.965 rows=49720 loops=2)')
Row(Index=24, _1='                                        Buckets: 131072  Batches: 1  Memory Usage: 12768kB')
Row(Index=25, _1='                                        Buffers: shared hit=1808')
Row(Index=26, _1='                                        ->  Parallel Seq Scan on olist_orders oo_1  (cost=0.00..2329.13 rows=52113 width=104) (actual time=0.010..5.221 rows=49720 loops=2)')
Row(Index=27, _1='                                              Buffers: shared hit=1808')
Row(Index=28, _1='  ->  Merge Left Join  (cost=49439.24..82889.61 rows=84100 width=174) (actual time=622.364..626.475 rows=20 loops=1)')
Row(Index=29, _1='        Merge Cond: (c.customer_id = ranked_1.customer_id)')
Row(Index=30, _1='        Buffers: shared hit=9037, temp read=5964 written=6790')
Row(Index=31, _1='        ->  Merge Left Join  (cost=32505.35..55009.24 rows=84100 width=144) (actual time=505.006..505.137 rows=20 loops=1)')
Row(Index=32, _1='              Merge Cond: (c.customer_id = can.customer_id)')
Row(Index=33, _1='              Buffers: shared hit=4005, temp read=5125 written=5790')
Row(Index=34, _1='              ->  Merge Left Join  (cost=29833.95..52124.59 rows=84100 width=112) (actual time=367.670..367.789 rows=20 loops=1)')
Row(Index=35, _1='                    Merge Cond: (c.customer_id = ranked.customer_id)')
Row(Index=36, _1='                    Buffers: shared hit=4005, temp read=3077 written=4515')
Row(Index=37, _1='                    ->  Merge Left Join  (cost=16510.67..28957.30 rows=84100 width=80) (actual time=294.231..294.306 rows=20 loops=1)')
Row(Index=38, _1='                          Merge Cond: (c.customer_id = stage2_rmf.customer_id)')
Row(Index=39, _1='                          Buffers: shared hit=4005, temp read=1275 written=3317')
Row(Index=40, _1='                          ->  Index Scan using olist_customers_pkey on olist_customers c  (cost=0.42..10897.92 rows=84100 width=44) (actual time=0.010..0.040 rows=20 loops=1)')
Row(Index=41, _1='                                Buffers: shared hit=23')
Row(Index=42, _1='                          ->  Subquery Scan on stage2_rmf  (cost=16510.25..17846.63 rows=200 width=68) (actual time=294.217..294.252 rows=20 loops=1)')
Row(Index=43, _1='                                Buffers: shared hit=3982, temp read=1275 written=3317')
Row(Index=44, _1='                                ->  GroupAggregate  (cost=16510.25..17843.13 rows=200 width=64) (actual time=294.207..294.230 rows=20 loops=1)')
Row(Index=45, _1='                                      Group Key: ot.customer_id')
Row(Index=46, _1='                                      Buffers: shared hit=3982, temp read=1275 written=3317')
Row(Index=47, _1='                                      InitPlan 2 (returns $2)')
Row(Index=48, _1='                                        ->  Aggregate  (cost=2915.40..2915.42 rows=1 width=4) (actual time=12.436..12.438 rows=1 loops=1)')
Row(Index=49, _1='                                              Buffers: shared hit=1808')
Row(Index=50, _1='                                              ->  Seq Scan on olist_orders  (cost=0.00..2693.92 rows=88592 width=8) (actual time=0.012..6.535 rows=99441 loops=1)')
Row(Index=51, _1='                                                    Buffers: shared hit=1808')
Row(Index=52, _1='                                      ->  Sort  (cost=13594.84..13816.32 rows=88592 width=92) (actual time=281.753..281.759 rows=21 loops=1)')
Row(Index=53, _1='                                            Sort Key: ot.customer_id, ot.order_id')
Row(Index=54, _1='                                            Sort Method: external merge  Disk: 9552kB')
Row(Index=55, _1='                                            Buffers: shared hit=2174, temp read=1275 written=3317')
Row(Index=56, _1='                                            ->  CTE Scan on stage1_orders_total ot  (cost=0.00..1771.84 rows=88592 width=92) (actual time=66.212..218.525 rows=99441 loops=1)')
Row(Index=57, _1='                                                  Buffers: shared hit=2174, temp read=796 written=2120')
Row(Index=58, _1='                    ->  Materialize  (cost=13323.28..22951.50 rows=443 width=64) (actual time=73.436..73.471 rows=20 loops=1)')
Row(Index=59, _1='                          Buffers: temp read=1802 written=1198')
Row(Index=60, _1='                          ->  Subquery Scan on ranked  (cost=13323.28..22950.39 rows=443 width=64) (actual time=73.433..73.464 rows=20 loops=1)')
Row(Index=61, _1='                                Filter: (ranked.rn_recent = 1)')
Row(Index=62, _1='                                Buffers: temp read=1802 written=1198')
Row(Index=63, _1='                                ->  WindowAgg  (cost=13323.28..21842.99 rows=88592 width=112) (actual time=73.432..73.461 rows=20 loops=1)')
Row(Index=64, _1='                                      Filter: ((row_number() OVER (?)) <= 1)')
Row(Index=65, _1='                                      Buffers: temp read=1802 written=1198')
Row(Index=66, _1='                                      ->  Incremental Sort  (cost=13323.28..20292.63 rows=88592 width=96) (actual time=73.417..73.420 rows=21 loops=1)')
Row(Index=67, _1='                                            Sort Key: ot_1.customer_id, ot_1.order_purchase_timestamp')
Row(Index=68, _1='                                            Presorted Key: ot_1.customer_id')
Row(Index=69, _1='                                            Full-sort Groups: 1  Sort Method: quicksort  Average Memory: 28kB  Peak Memory: 28kB')
Row(Index=70, _1='                                            Buffers: temp read=1802 written=1198')
Row(Index=71, _1='                                            ->  WindowAgg  (cost=13293.84..15287.16 rows=88592 width=96) (actual time=73.382..73.399 rows=33 loops=1)')
Row(Index=72, _1='                                                  Run Condition: (row_number() OVER (?) <= 1)')
Row(Index=73, _1='                                                  Buffers: temp read=1802 written=1198')
Row(Index=74, _1='                                                  ->  Sort  (cost=13293.84..13515.32 rows=88592 width=88) (actual time=73.373..73.378 rows=33 loops=1)')
Row(Index=75, _1='                                                        Sort Key: ot_1.customer_id, ot_1.order_purchase_timestamp DESC, ot_1.order_id DESC')
Row(Index=76, _1='                                                        Sort Method: external merge  Disk: 9552kB')
Row(Index=77, _1='                                                        Buffers: temp read=1802 written=1198')
Row(Index=78, _1='                                                        ->  CTE Scan on stage1_orders_total ot_1  (cost=0.00..1771.84 rows=88592 width=88) (actual time=0.038..10.143 rows=99441 loops=1)')
Row(Index=79, _1='                                                              Buffers: temp read=1323 written=1')
Row(Index=80, _1='              ->  Sort  (cost=2671.40..2671.90 rows=200 width=64) (actual time=137.330..137.335 rows=20 loops=1)')
Row(Index=81, _1='                    Sort Key: can.customer_id')
Row(Index=82, _1='                    Sort Method: external merge  Disk: 4488kB')
Row(Index=83, _1='                    Buffers: temp read=2048 written=1275')
Row(Index=84, _1='                    ->  Subquery Scan on can  (cost=2657.76..2663.76 rows=200 width=64) (actual time=33.587..73.857 rows=99441 loops=1)')
Row(Index=85, _1='                          Buffers: temp read=1684 written=712')
Row(Index=86, _1='                          ->  HashAggregate  (cost=2657.76..2661.76 rows=200 width=64) (actual time=33.586..68.041 rows=99441 loops=1)')
Row(Index=87, _1='                                Group Key: stage1_orders_total.customer_id')
Row(Index=88, _1='                                Batches: 5  Memory Usage: 9025kB  Disk Usage: 3600kB')
Row(Index=89, _1='                                Buffers: temp read=1684 written=712')
Row(Index=90, _1='                                ->  CTE Scan on stage1_orders_total  (cost=0.00..1771.84 rows=88592 width=64) (actual time=0.007..7.119 rows=99441 loops=1)')
Row(Index=91, _1='                                      Buffers: temp read=1323')
Row(Index=92, _1='        ->  Materialize  (cost=16933.89..27036.87 rows=200 width=80) (actual time=117.351..121.322 rows=20 loops=1)')
Row(Index=93, _1='              Buffers: shared hit=5032, temp read=839 written=1000')
Row(Index=94, _1='              ->  Subquery Scan on ranked_1  (cost=16933.89..27036.37 rows=200 width=80) (actual time=117.348..121.315 rows=20 loops=1)')
Row(Index=95, _1='                    Filter: (ranked_1.rn = 1)')
Row(Index=96, _1='                    Buffers: shared hit=5032, temp read=839 written=1000')
Row(Index=97, _1='                    ->  WindowAgg  (cost=16933.89..26536.37 rows=40000 width=88) (actual time=117.347..121.312 rows=20 loops=1)')
Row(Index=98, _1='                          Run Condition: (row_number() OVER (?) <= 1)')
Row(Index=99, _1='                          Buffers: shared hit=5032, temp read=839 written=1000')
Row(Index=100, _1='                          ->  Incremental Sort  (cost=16933.89..25736.37 rows=40000 width=80) (actual time=117.342..121.297 rows=20 loops=1)')
Row(Index=101, _1="                                Sort Key: oo.customer_id, ((sum((COALESCE(oi.price, '0'::numeric) + COALESCE(oi.freight_value, '0'::numeric))))::numeric(12,2)) DESC, op.product_category_name")
Row(Index=102, _1='                                Presorted Key: oo.customer_id')
Row(Index=103, _1='                                Full-sort Groups: 1  Sort Method: quicksort  Average Memory: 27kB  Peak Memory: 27kB')
Row(Index=104, _1='                                Buffers: shared hit=5032, temp read=839 written=1000')
Row(Index=105, _1='                                ->  Finalize GroupAggregate  (cost=16892.19..23703.60 rows=40000 width=80) (actual time=117.294..121.277 rows=33 loops=1)')
Row(Index=106, _1='                                      Group Key: oo.customer_id, op.product_category_name')
Row(Index=107, _1='                                      Buffers: shared hit=5032, temp read=839 written=1000')
Row(Index=108, _1='                                      ->  Gather Merge  (cost=16892.19..22703.60 rows=40000 width=96) (actual time=117.288..121.256 rows=34 loops=1)')
Row(Index=109, _1='                                            Workers Planned: 1')
Row(Index=110, _1='                                            Workers Launched: 1')
Row(Index=111, _1='                                            Buffers: shared hit=5032, temp read=839 written=1000')
Row(Index=112, _1='                                            ->  Partial GroupAggregate  (cost=15892.18..17203.59 rows=40000 width=96) (actual time=114.256..114.408 rows=242 loops=2)')
Row(Index=113, _1='                                                  Group Key: oo.customer_id, op.product_category_name')
Row(Index=114, _1='                                                  Buffers: shared hit=5032, temp read=839 written=1000')
Row(Index=115, _1='                                                  ->  Sort  (cost=15892.18..16054.46 rows=64913 width=96) (actual time=114.243..114.272 rows=294 loops=2)')
Row(Index=116, _1='                                                        Sort Key: oo.customer_id, op.product_category_name')
Row(Index=117, _1='                                                        Sort Method: external merge  Disk: 4408kB')
Row(Index=118, _1='                                                        Buffers: shared hit=5032, temp read=839 written=1000')
Row(Index=119, _1='                                                        Worker 0:  Sort Method: external merge  Disk: 3576kB')
Row(Index=120, _1='                                                        ->  Hash Left Join  (cost=4086.15..7375.11 rows=64913 width=96) (actual time=30.489..71.556 rows=56712 loops=2)')

In [15]:
execute_sql("""
EXPLAIN (ANALYZE, BUFFERS)
WITH target_customer AS (
    SELECT customer_id
    FROM olist_customers
    ORDER BY customer_id
    LIMIT 1
)
SELECT mv.*
FROM mv_olist_customer_features AS mv
JOIN target_customer AS t
    ON t.customer_id = mv.customer_id;
""")

======================================================================
Statement 1/1
======================================================================
EXPLAIN (ANALYZE, BUFFERS)
WITH target_customer AS (
    SELECT customer_id
    FROM olist_customers
    ORDER BY customer_id
    LIMIT 1
)
SELECT mv.*
FROM mv_olist_customer_features AS mv
JOIN target_customer AS t
    ON t.customer_id = mv.customer_id;
----------------------------------------------------------------------

                                           QUERY PLAN
0   Nested Loop  (cost=0.83..8.98 rows=1 width=174...
1                        Buffers: shared hit=5 read=3
2     ->  Limit  (cost=0.42..0.55 rows=1 width=32)...
3                               Buffers: shared hit=4
4           ->  Index Only Scan using olist_custom...
5                                     Heap Fetches: 1
6                               Buffers: shared hit=4
7     ->  Index Scan using idx_mv_olist_customer_f...
8           Index Cond: (customer_id = olist_custo...
9                        Buffers: shared hit=1 read=3
10                                          Planning:
11                              Buffers: shared hit=7
12                            Planning Time: 0.199 ms
13                           Execution Time: 0.065 ms

Finished successfully: 1 statement(s) executed.

In [16]:
execute_sql("""
CREATE INDEX IF NOT EXISTS idx_mv_olist_customer_features_monetary
    ON mv_olist_customer_features (monetary DESC);

EXPLAIN (ANALYZE, BUFFERS)
SELECT *
FROM mv_olist_customer_features
ORDER BY monetary DESC NULLS LAST
LIMIT 10;
""")

======================================================================
Statement 1/2
======================================================================
CREATE INDEX IF NOT EXISTS idx_mv_olist_customer_features_monetary
    ON mv_olist_customer_features (monetary DESC);
----------------------------------------------------------------------
Command executed successfully.

======================================================================
Statement 2/2
======================================================================
EXPLAIN (ANALYZE, BUFFERS)
SELECT *
FROM mv_olist_customer_features
ORDER BY monetary DESC NULLS LAST
LIMIT 10;
----------------------------------------------------------------------

                                           QUERY PLAN
0   Limit  (cost=4449.01..4450.16 rows=10 width=17...
1                            Buffers: shared hit=1636
2     ->  Gather Merge  (cost=4449.01..11175.94 ro...
3                                  Workers Planned: 1
4                                 Workers Launched: 1
5                            Buffers: shared hit=1636
6           ->  Sort  (cost=3449.00..3595.24 rows=...
7                  Sort Key: monetary DESC NULLS LAST
8                 Sort Method: top-N heapsort  Mem...
9                            Buffers: shared hit=1636
10                Worker 0:  Sort Method: top-N he...
11                ->  Parallel Seq Scan on mv_olis...
12                           Buffers: shared hit=1600
13                                          Planning:
14                       Buffers: shared hit=4 read=1
15                            Planning Time: 0.116 ms
16                          Execution Time: 10.093 ms

Finished successfully: 2 statement(s) executed.

## Reflection

Плани `EXPLAIN (ANALYZE, BUFFERS)` знято після повного запуску на 99 441 клієнті Olist. CTE-запит із `LIMIT 20` виконувався 635,124 мс, а пошук одного клієнта в MV — 0,065 мс. Запити роблять різну роботу, тож це не строге порівняння, але ціну переобчислення проти точкового читання видно добре.

Найдорожче в плані обходиться блок RFM, передусім `monetary`. Для нього треба з'єднати `orders` з `order_items`, а в `stage1_orders_total` згрупувати всі 99 441 замовлення. Тут у плані є `Parallel Hash Right Join`, `Finalize GroupAggregate` і дискове сортування `external merge`. `GroupAggregate` у гілці RFM віддає перші рядки лише приблизно на 294 мс, і наступне сортування теж іде на диск. Rolling AOV за 30 днів додає `WindowAgg` з `Incremental Sort`, а для категорії потрібні ще один JOIN, агрегація й ранжування. Тобто час іде на сканування, групування й сортування, а не на різницю дат для recency.

Кешувати ці ознаки в MV має сенс, якщо їх багато разів читають для навчання чи сервінгу: важкі JOIN і агрегації виконуються один раз під час створення або refresh, а lookup іде через `Index Scan` по унікальному `customer_id`. Я б оновлював MV щодоби після завантаження нових замовлень; для статичного історичного Olist вистачить refresh на вимогу. Звичайний VIEW кращий для рідкісних запитів, коли потрібні найсвіжіші дані, а затримка не критична. Мінуси MV — зайве місце на диску й ризик прочитати застарілі значення; до того ж top-N запит до неї тут все одно дає `Parallel Seq Scan` і `Sort`.

Рекурсія зупиняється завдяки умові `referred_customer_id <> ALL(path)` і ліміту `depth < 20`. Якщо в графі є цикл A → B → A, повторний A не пройде перевірку шляху, тож обхід не стане нескінченним. Щоправда, з anchor через `NOT EXISTS` ізольований цикл без кореня в результат не потрапить. Головний компроміс цього пайплайна — швидкість повторних читань проти свіжості ознак; витрати на refresh і зберігання залежать від того, як часто треба оновлюватися.